language: ruby

sudo: false

cache: bundler

rvm:
  - 2.1.5

jdk:
  - oraclejdk8

script:
  - RAILS_ENV=test bundle exec rake test

notifications:
  slack: seek4science:Jds9srWlt27UZUoD3MnJoUWb
  email:
    recipients:
      - thucquyendn@gmail.com
    on_failure: change
    on_success: never
