language: ruby

sudo: false

cache: bundler

rvm:
  - 2.1.9

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - RAILS_ENV=test bundle exec rake test

notifications:
  slack:
    secure: fK3kbDHg/kwFCjxhFkg0wkOcwXoFwkfJJdRFwZQtnMDkY4yHNtr9SWIHWOiI9OceNgWLeHwvvm/7737WBWnTf4RF3mn0/D9xYtOn+DfV2gb1xXVjDb33oBQWrFN8P1x4xFNOMw38LQ46NYvsv6bfPmZRJpKuvHPVJUsBCINx14w=
  email:
    recipients:
      - thucquyendn@gmail.com
    on_failure: change
    on_success: never
