language: ruby

sudo: false

cache: bundler

rvm:
  - 2.1.5

script:
  - RAILS_ENV=test bundle exec rake test

notifications:
  email:
    recipients:
      - thucquyendn@gmail.com
    on_failure: change
    on_success: never